app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('login', 'UsersController@getLogin');
Route::post('login', 'UsersController@postLogin');
Route::get('logout', 'UsersController@getLogout')->before('auth');
Route::get('sign-up', 'UsersController@getRegister');
Route::post('sign-up', 'UsersController@postRegister');
Route::get('forgot-password', 'UsersController@getForgot');
Route::post('forgot-password', 'UsersController@postForgot');
Route::get('password/reset/{token}', 'UsersController@getReset');
Route::post('password/reset/{token}', 'UsersController@postReset');
Route::get('active/{reset_token}', array('uses'=>'UsersController@getActive','as'=>'activate'));

Route::group(array('prefix'=>'my','before'=>'auth'), function() {
  Route::get('edit-profile', 'UsersController@getProfile');
  Route::post('edit-profile', 'UsersController@postProfile');
  Route::get('change-password', 'UsersController@getChangePassword');
  Route::post('change-password', 'UsersController@postChangePassword');
  Route::get('courses', 'UsersController@getCourse');
});


Route::get('admin/login', 'Admin_SessionsController@getLogin');
Route::post('admin/login', 'Admin_SessionsController@postLogin');
Route::get('admin/change-pass','Admin_SessionsController@getChangePassword')->before('admin_auth');
Route::post('admin/change-pass','Admin_SessionsController@postChangePassword')->before('admin_auth');
Route::get('admin/logout', 'Admin_SessionsController@getLogout')->before('admin_auth');





Route::group(array('prefix'=>'admin','before'=>'admin_auth'), function() {

  Route::get('/', 'Admin_DashboardController@getIndex');
  Route::controller('news_categories', 'Admin_NewsCategoriesController');
  Route::resource('news','Admin_NewsController');
  Route::controller('course_categories', 'Admin_CourseCategoriesController');
  Route::resource('courses','Admin_CoursesController');
  Route::resource('inquiries','Admin_InquiriesController',array('except'=>array('show,edit,update')));
  Route::controller('settings', 'Admin_SettingsController');
  Route::resource('contents','Admin_ContentsController',array('except'=>array('show')));
  Route::resource('resources', 'Admin_ResourcesController');
  Route::resource('subscribes','Admin_SubscribesController');
});


Route::get('/', 'HomeController@getIndex');
Route::get('news', array('uses'=>'NewsController@getIndex'));
Route::get('news/{id}-{slug}', array('uses'=>'NewsController@getView'))
   ->where(array('id'=>'[0-9]+'));
Route::get('resources', array('uses'=>'ResourcesController@getIndex'));
Route::get('download/{file}', array('uses'=>'ResourcesController@getDownload'));
Route::controller('contact-us','InquiriesController');
Route::get('about-us', array('uses'=>'HomeController@getAbout'));
Route::get('for-providers', array('uses'=>'HomeController@getProvider'));
Route::get('choose-training', array('uses'=>'CoursesController@getChoose'));
Route::post('subscribes', array('uses'=>'SubscribesController@postIndex','as'=>'subscribes'));
Route::get('terms-and-conditions', array('uses'=>'HomeController@getTerms'));
Route::get('thankyou', array('uses'=>'HomeController@getThankyou','as'=>'thankyou'));
Route::get('courses', array('uses'=>'CoursesController@getIndex','as'=>'listing'));


// ===============================================
	// 404 ===========================================
	// ===============================================

	App::missing(function($exception)
	{

		// shows an error page (app/views/error.blade.php)
		// returns a page not found error
		return Response::view("error.notfound");
	});

app/models/Subscribe.php
<?php

class Subscribe extends Eloquent {
	
	protected $table = "subscribes";

	protected $fillable = array('email','ip','ua');	
    
    public $timestamps = true;

     public function getDates() {
        return array('created_at');
    }

}

app/controllers/Admin/SubscribesController.php
<?php

class Admin_SubscribesController extends Admin_BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$query = Subscribe::query();
	    if(Input::get('id')) $query->where('id','=', Input::get('id'));
	    if(Input::get('email')) $query->where('email','LIKE', Input::get('email'));
	    $row = new Subscribe(Input::old());
	    $rows = $query->paginate();    
	    $this->layout->content = View::make('admin.subscribes.list', compact('rows','row'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		//
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$rows=Subscribe::all()->find($id);
        $this->layout->content = View::make('admin.subscribes.detail', compact('rows'));
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$subscription = Subscribe::find($id);
	    $subscription->delete();
	    if(Request::ajax())
	      return Response::json('OK');
	    else
	      return Redirect::route('admin.subscribes.index');
	}


}

app/controllers/SubscribesController.php
<?php

class SubscribesController extends BaseController {
	public $restful = true;

	public function postIndex() {

        $rules = array(
            'email' => 'required|email|unique:subscribes',
        );
        $messages = array(
            'email.required' => 'Please enter your email address',
            'email' => 'Please enter valid email address',
            );
        $validator = Validator::make(Input::all(), $rules, $messages);
        $data = Input::all();
         if(Request::ajax())
        {
            if ($validator->passes()) {
                $subscription = new Subscribe;
                $subscription->email = $data['email'];
                $subscription->ip = Request::getClientIp();
                $subscription->ua = $_SERVER['HTTP_USER_AGENT'];

                $subscription->save();
                Mail::send('emails.subscription', array(), function($message) {
                            $message->from(Config::get('site.email'), Config::get('site.name'));
                            $message->to('nicolecross1579@gmail.com');
                            $message->bcc('sam@etraffic.com.au');
                            $message->subject('New Subscription for newsletters from ' . Config::get('site.name'));
                        });


                Mail::send('emails.subscription_ack', array(), function($message) use($subscription) {
                            $message->from(Config::get('site.email'), Config::get('site.name'));
                            $message->to($subscription->email);
                            $message->subject('Thankyou for subscribing to our newsletters.');
                        });

                return 'ok';
            }
            else{
                return $validator->messages()->get('email');
            }
        }


	}

}

app/views/admin/subscribes/detail.blade.php
@section('title')
	 Newsletter Subscription Detail 
@stop
@section('content')
<div class="row"> 
  <div class="col-lg-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Subscription Detail
      </div>
      <div class="panel-body">        
        @if(count($rows))
          <table class="table table-condensed table-striped" id="grid">
            
            <tbody>

              <tr><td colspan="2"><h3>Subscription Details:</h3></td></tr>
	             <tr>
	                  <td width="200"> Email:</td>
	                  <td>{{$rows->email?$rows->email : '-'}}</td>                 
	              </tr>
	              <tr>
	                  <td width="200">IP:</td>
	                  <td>{{$rows->ip?$rows->ip : '-'}}</td>                 
	              </tr>
	               <tr>
	                  <td width="200">User Agent:</td>
	                  <td>{{$rows->ua?$rows->ua : '-'}}</td>                 
	              </tr>
                <tr>
                  <td width="200">Created at:</td>
                  <td>{{ $rows->created_at->format('j F Y H:i:s') }}</td>
                </tr>
	             
            </tbody>
          </table>          
         
        
        @endif

      </div>
    </div>
  </div>
  <div class="list-map">
  <div id="map" style="height: 275px;"></div>
  </div>
  
@stop

app/views/admin/subscribes/list.blade.php
@section('title')
    Newsletters Subscription
@stop
@section('content')
<div class="row"> 
  <div class="col-lg-9">
    <div class="panel panel-default">
      <div class="panel-heading">

        Subscriptions
          
   
      </div>
      <div class="panel-body">        
        @if(count($rows))
          <table class="table table-condensed table-striped" id="grid">
            <thead>
              <tr>
                <th class="text-right" width="50">ID</th>                
                <th>Email</th> 
                <th class="text-center" width="150">Actions</th>
              </tr>
            </thead>
            <tbody>
              @foreach($rows as $row)
              <tr data-id="{{$row->id}}">
                <td align="right">{{$row->id}}</td>
                <td>{{ $row->email }} </td>
                <td align="center">
                  {{ link_to_route("admin.subscribes.show","Details",array($row->id),array('class'=>'btn btn-xs btn-default')) }}
                  {{ link_to_route("admin.subscribes.destroy","Delete",array($row->id),array('class'=>'btn btn-xs btn-danger','data-method'=>"delete")) }}
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>          
          @include('admin.shared.paging')
        @else
          <p class="alert alert-warning">No results to display</p>
        @endif

      </div>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="panel panel-default">
      <div class="panel-heading">Filters</div>
      <div class="panel-body">
        {{ Former::open_vertical()->method('GET') }}
        {{ Former::text('id')->label('ID') }}
        {{ Former::text('email') }}
        {{ Former::actions()->success_submit('Filter')->small_link('Reset',URL::to('/admin/subscribes')) }}
        {{ Former::close() }}
      </div>
    </div>
  </div>
</div>

@stop