app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('login', 'UsersController@getLogin');
Route::post('login', 'UsersController@postLogin');
Route::get('logout', 'UsersController@getLogout')->before('auth');
Route::get('sign-up', 'UsersController@getRegister');
Route::post('sign-up', 'UsersController@postRegister');
Route::get('forgot-password', 'UsersController@getForgot');
Route::post('forgot-password', 'UsersController@postForgot');
Route::get('password/reset/{token}', 'UsersController@getReset');
Route::post('password/reset/{token}', 'UsersController@postReset');
Route::get('active/{reset_token}', array('uses'=>'UsersController@getActive','as'=>'activate'));

Route::group(array('prefix'=>'my','before'=>'auth'), function() {
  Route::get('edit-profile', 'UsersController@getProfile');
  Route::post('edit-profile', 'UsersController@postProfile');
  Route::get('change-password', 'UsersController@getChangePassword');
  Route::post('change-password', 'UsersController@postChangePassword');
  Route::get('courses', 'UsersController@getCourse');
});


Route::get('admin/login', 'Admin_SessionsController@getLogin');
Route::post('admin/login', 'Admin_SessionsController@postLogin');
Route::get('admin/change-pass','Admin_SessionsController@getChangePassword')->before('admin_auth');
Route::post('admin/change-pass','Admin_SessionsController@postChangePassword')->before('admin_auth');
Route::get('admin/logout', 'Admin_SessionsController@getLogout')->before('admin_auth');





Route::group(array('prefix'=>'admin','before'=>'admin_auth'), function() {

  Route::get('/', 'Admin_DashboardController@getIndex');
  Route::controller('news_categories', 'Admin_NewsCategoriesController');
  Route::resource('news','Admin_NewsController');
  Route::controller('course_categories', 'Admin_CourseCategoriesController');
  Route::resource('courses','Admin_CoursesController');
  Route::resource('inquiries','Admin_InquiriesController',array('except'=>array('show,edit,update')));
  Route::controller('settings', 'Admin_SettingsController');
  Route::resource('contents','Admin_ContentsController',array('except'=>array('show')));
  Route::resource('resources', 'Admin_ResourcesController');
  Route::resource('subscribes','Admin_SubscribesController');
});


Route::get('/', 'HomeController@getIndex');
Route::get('news', array('uses'=>'NewsController@getIndex'));
Route::get('news/{id}-{slug}', array('uses'=>'NewsController@getView'))
   ->where(array('id'=>'[0-9]+'));
Route::get('resources', array('uses'=>'ResourcesController@getIndex'));
Route::get('download/{file}', array('uses'=>'ResourcesController@getDownload'));
Route::controller('contact-us','InquiriesController');
Route::get('about-us', array('uses'=>'HomeController@getAbout'));
Route::get('for-providers', array('uses'=>'HomeController@getProvider'));
Route::get('choose-training', array('uses'=>'CoursesController@getChoose'));
Route::post('subscribes', array('uses'=>'SubscribesController@postIndex','as'=>'subscribes'));
Route::get('terms-and-conditions', array('uses'=>'HomeController@getTerms'));
Route::get('thankyou', array('uses'=>'HomeController@getThankyou','as'=>'thankyou'));
Route::get('courses', array('uses'=>'CoursesController@getIndex','as'=>'listing'));


// ===============================================
	// 404 ===========================================
	// ===============================================

	App::missing(function($exception)
	{

		// shows an error page (app/views/error.blade.php)
		// returns a page not found error
		return Response::view("error.notfound");
	});

app/views/admin/resources/form.blade.php
@section('title')
{{ 'Resource' }}
@stop
@section('content')
<div class="row"> 
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
       Resource   
      </div>
      <div class="panel-body">        
      
         @include("admin.shared.errors")
          {{
            Former::horizontal_open()->action($edit? URL::route("admin.resources.update",array($id)) : URL::route("admin.resources.store") )->method($edit? 'put':'post')
          }}
          {{ Former::text("title")->help("255 characters max") }}
          {{ Former::radio('type','')->radios(assoc_to_radios(Resource::$types,'type'))->inline()->check('pdf')->label("Select Resource type")->class('type') }}
        <div id="pdf">
           
        {{ Former::hidden('pdf')->id('photo') }}
        {{ Former::file('pdf_upload','PDF') }}
        </div>
        <div id="link">
          {{ Former::url("link")->help("255 characters max") }}  
        </div>  
        <div class="col-sm-offset-2 col-sm-10"> 
          {{ Form::hidden('status',0) }}
          {{ Former::checkbox('status','')->value(1)->text('Show this resource on website?')->check() }}
        </div>      
        {{ Former::actions()->success_submit('Submit')->small_link('Back',(Input::get('next')? Input::get('next'):"/{$prefix}/{$controller}")) }}
        {{ Former::close() }}
      </div>
    </div>
  </div>  
</div>

@stop

@section('scripts')
<script>
$(document).ready(function() {
  var type = '';
  $('#link').hide();
  $('#pdf').show();
  $('input[type=radio][name=type]').click(function(){

    if(document.getElementById('type_pdf').checked)
    {
      type = document.getElementById('type_pdf').value;
    }
    else{
      type = document.getElementById('type_link').value;
    }
    
    if(type=="pdf"){
      $('#link').hide();
      $('#pdf').show();
    }
    else{
      $('#pdf').hide();
      $('#link').show();
    }

  });
  

  $('#pdf_upload').uploadify({
        'multi': false,
        'auto': true,
        'fileTypeDesc' : 'PDF File',
        'fileTypeExts' : '*.pdf',
        'cancelImg': '{{ asset("/a/misc/uploadify-cancel.png") }}',
        'swf': '{{ asset("/a/misc/uploadify.swf") }}',
        'uploader': '{{ asset("/a/misc/uploadify.php") }}',
        onUploadSuccess: function(file, data, response) {
        $('#photo').val(data);
        }
  });
});
</script>

@stop

app/views/admin/resources/list.blade.php
@section('title')
{{ 'Resources' }}
@stop
@section('content')
<div class="row"> 
  <div class="col-lg-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Resources
        {{ link_to_route('admin.resources.create',"Add",array(),array('class'=>'pull-right btn btn-xs btn-primary')) }}
      </div>
      <div class="panel-body">        
        @if(count($rows))
          <table class="table table-condensed table-striped" id="grid">
            <thead>
              <tr>
                <th width="30">Id</th>
                <th>Title</th>
                <th width="50">Type</th>
                <th width="120">Action</th>
              </tr>
            </thead>
            <tbody>
              @foreach($rows as $row)
              <tr data-id="{{$row->id}}">
                <td align="right">{{$row->id}}</td>
                <td>{{$row->title}}</td>                                                                
                <td>{{$row->type}}</td>
                <td align="center">
                  
                  {{ link_to_route("admin.resources.edit","Edit",array($row->id), array('class'=>'btn btn-xs btn-primary')) }}
                  {{ link_to_route("admin.resources.destroy","Delete",array($row->id), array('class'=>'btn btn-xs btn-danger','data-method'=>'delete')) }}
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>          
          @include('admin.shared.paging')
        @else
          <p class="alert alert-warning">No results to display</p>
        @endif

      </div>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="panel panel-default">
      <div class="panel-heading">Filters</div>
      <div class="panel-body">
        {{ Former::open_vertical()->method('GET') }}
        {{ Former::text("id")->label("ID") }}      
        {{ Former::text("title","Title") }}
        {{ Former::select("type","Published")->options( array(''=>'-- ANY --','1'=>'Yes','0'=>'No') )  }}
        {{ Former::actions()->success_submit('Filter')->small_link('Reset',URL::current()) }}
        {{ Former::close() }}
      </div>
    </div>
  </div>
</div>
@stop